### ISSUE TITLE
MultiSelect + ActionPopover: Edge 44 is not supported

### ISSUE THREAD

**Issue by konrazem** [Sage/carbon#3852]
### Current behaviour

When using Edge 44 browser, click on MultiSelect or ActionPopover button makes crush of the component

```
'ResizeObserver' is not defined
ReferenceError: 'ResizeObserver' is not defined
   at Popover (https://carbon.sage.com/main.53c6a37bbf208e141135.bundle.js:1:1166871)
   at Ih (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2639154)
   at gk (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2683960)
   at fk (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2669773)
   at Zj (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2669706)
   at Lj (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2667082)
   at Anonymous function (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2625626)
   at exports.unstable_runWithPriority (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2700185)
   at fg (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2625322)
   at ig (https://carbon.sage.com/vendors~main.53c6a37bbf208e141135.bundle.js:1:2625573)
```

### Expected behaviour

Menu is opened after click on a button

### Reproducible example

Test storybook in Edge 44 
[https://carbon.sage.com/?path=/story/design-system-select-multiselect--default-story](https://carbon.sage.com/?path=/story/design-system-select-multiselect--default-story)

[https://carbon.sage.com/?path=/story/design-system-action-popover-test--default](https://carbon.sage.com/?path=/story/design-system-action-popover-test--default)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 68.0.2 
| carbon-factory   |  11.0.1
| react-scripts    | 
| React            | 16.13.1
| Browser          |  Edge 44.18362.449.0
| npm              |  6.14.8
| Operating System | Windows 10

**Comment by grabkowski** [comment]
HI @konrazem, this version of Edge is no longer supported in Carbon (looks like it's the last non Chromium version), we advise you to update that browser to the latest version.
