### ISSUE TITLE
Postinstall script blocked by rate limit on Bitrise

### ISSUE THREAD

**Issue by tboulis** [Sage/carbon#5204]
### Current behaviour

When we run `yarn install` on Bitrise to install dependencies, when carbon is installed it throws this error:
```
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR /Users/vagrant/git/node_modules/@octokit/request/dist-node/index.js:86
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       const error = new requestError.RequestError(toErrorMessage(data), status, {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR                     ^
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR 
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR RequestError [HttpError]: API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     at /Users/vagrant/git/node_modules/@octokit/request/dist-node/index.js:86:21
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     at processTicksAndRejections (node:internal/process/task_queues:96:5)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     at async getOpenRfcs (/Users/vagrant/git/node_modules/carbon-react/scripts/check_rfcs.js:18:20)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     at async checkRfcs (/Users/vagrant/git/node_modules/carbon-react/scripts/check_rfcs.js:36:20) {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR   status: 403,
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR   response: {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     url: '[https://api.github.com/repos/sage/carbon/pulls',](https://api.github.com/repos/sage/carbon/pulls)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     status: 403,
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     headers: {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'access-control-allow-origin': '*',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       connection: 'close',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'content-length': '280',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'",
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'content-type': 'application/json; charset=utf-8',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       date: 'Mon, 06 Jun 2022 08:06:33 GMT',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       server: 'Varnish',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-content-type-options': 'nosniff',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-frame-options': 'deny',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-github-media-type': 'github.v3; format=json',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-github-request-id': 'BA23:2C5E:3D1997E:71EB924:629DB589',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-ratelimit-limit': '60',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-ratelimit-remaining': '0',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-ratelimit-reset': '1654503620',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-ratelimit-resource': 'core',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-ratelimit-used': '60',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'x-xss-protection': '1; mode=block'
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     },
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     data: {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       message: "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       documentation_url: '[https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     }
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR   },
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR   request: {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     method: 'GET',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     url: '[https://api.github.com/repos/sage/carbon/pulls',](https://api.github.com/repos/sage/carbon/pulls)
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     headers: {
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       accept: 'application/vnd.github.v3+json',
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR       'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/16.15.0 (darwin; x64)'
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     },
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR     request: { hook: [Function: bound bound register] }
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR   }
➤ YN0000: │ carbon-react@npm:106.3.1 [573bf] STDERR }
```
where `XXX.XXX.XXX.XXX` is the same IP address on all build attempts. 
It seems to be triggered by this postinstall script carbon-react has: https://github.com/Sage/carbon/blob/master/package.json#L30

### Expected behaviour

The postinstall script should not throw an error

### CodeSandbox or Storybook URL

Does not apply

### Suggested Solution

My colleague @quinnturner suggested that you should use https://github.com/watson/ci-info for the postinstall script. If a CI shares agents/public ips (such as Bitrise), GitHub may rate limit the requests and break the installation. ci-info supports checks for like ci.isCI or more specific ones like ci.BITRISE / ci.XYZ if you want to run it on some CIs but not others.

### Carbon Version

106.3.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Linux

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by DipperTheDan** [comment]
FE-5205
