### ISSUE TITLE
Failed prop type: Invalid prop `variant` of value `alternate` supplied to `Link`

### ISSUE THREAD

**Issue by johnb-sage** [Sage/carbon#6829]
### Description

Full error: 
`Warning: Failed prop type: Invalid prop 'variant' of value 'alternate' supplied to 'Link', expected one of ["default","negative","neutral"].
    at http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3024:23946
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.a
    at li
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.li
    at MenuItem (http://127.0.0.1:8080/932.b0e7ddb0.iframe.bundle.js:241:16006)
    at ul
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.ul
    at li
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.li
    at http://127.0.0.1:8080/932.b0e7ddb0.iframe.bundle.js:248:1535
    at ul
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.ul
    at div
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.div
    at http://127.0.0.1:8080/932.b0e7ddb0.iframe.bundle.js:241:1179
    at li
    at StyledComponent (http://127.0.0.1:8080/565.d522b14a.iframe.bundle.js:3362:1565947)
    at styled.li
    at MenuItem (http://127.0.0.1:8080/932.b0e7ddb0.iframe.bundle.js:241:16006)`

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-mpdkgw?file=src%2FApp.tsx

### Steps to reproduce

Open menu item two, which contains a link. Observe type error in console.
![Screenshot 2024-07-12 at 08 25 03](https://github.com/user-attachments/assets/af41d304-c4d5-4816-a5c2-d82bd4fd3adb)

### Carbon version

140.2.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

**Comment by edleeks87** [comment]
FE-6700
